@baseUrl = http://localhost:3000
@userId = 1
@roomId = 1
@mapId = 1

### AUTH REGISTER

POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "testuser_{{$timestamp}}",
  "password": "password123",
  "email": "test_{{$timestamp}}@example.com"
}

### AUTH LOGOUT

POST {{baseUrl}}/api/auth/logout
Accept: application/json

### GET USERS

GET {{baseUrl}}/api/users
Accept: application/json

### GET ME

GET {{baseUrl}}/api/users/me
Accept: application/json

### GET USER BY ID

GET {{baseUrl}}/api/users/{{userId}}
Accept: application/json

### PUT USER

PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json
Accept: application/json

{
  "username": "updatedUser",
  "email": "updated@example.com",
  "password": "newpassword123"
}

### DELETE USER

DELETE {{baseUrl}}/api/users/{{userId}}
Accept: application/json

### GET USER ROOMS

GET {{baseUrl}}/api/users/{{userId}}/rooms
Accept: application/json

### GET ROOMS

GET {{baseUrl}}/api/rooms
Accept: application/json

### GET ROOM BY ID

GET {{baseUrl}}/api/rooms/{{roomId}}
Accept: application/json

### PUT ROOM

PUT {{baseUrl}}/api/rooms/{{roomId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Room Name",
  "description": "Updated description"
}

### DELETE ROOM

DELETE {{baseUrl}}/api/rooms/{{roomId}}
Accept: application/json

### GET MAPS

GET {{baseUrl}}/api/maps/metadata
Accept: application/json

### GET METADATA BY MAPID

GET {{baseUrl}}/api/maps/{{mapId}}/metadata
Accept: application/json

###

